# Generated by Django 4.0.3 on 2022-04-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishrecord',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='fishrecord',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
