# Generated by Django 4.0.3 on 2022-04-01 13:27

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_fishrecord_latitude_fishrecord_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishrecord',
            name='image',
            field=models.ImageField(blank=True, upload_to=api.models.FishRecord.nameFile),
        ),
    ]
